### ISSUE TITLE
Farbbug

### ISSUE THREAD

**Issue by hannesa7x** [Umihan/Collid_3e#2]
@FabiSdr
Hallo Fabian,
ich habe dein Programm leider zu wenig ausführlich getestet. Wenn man mehrere Objekte erstellt haben jedoch alle die gleiche Farbe. Hast du eine Lösung dafür? LG H. Brugger

**Comment by FabiSdr** [comment]
Hallo,
Ich habe vom Simon gehört, dass es bei ihm auch dieses Problem gibt. Leider habe ich keine Ahnung woran das liegt, denn der Konstruktor müsste so passen.

**Comment by hannesa7x** [comment]
Das Problem liegt daran, dass die Objekte in der main alle gleich hintereinander erstellt werden. Schau dir mal die Random Klasse an. Vielleicht könntes du da fündig werden.
https://docs.microsoft.com/en-us/dotnet/api/system.random?view=netcore-3.1

**Comment by FabiSdr** [comment]
Achso ok...ich muss vor dem generieren der nächsten Farbe eine Pause von mindestens 15 Millisekunden einbauen oder?

**Comment by hannesa7x** [comment]
@FabiSdr genau, das sollte das Problem beheben.
LG H. Brugger

**Comment by hannesa7x** [comment]
#3 durch pull request Fehler behoben. Issue closed.
